### ISSUE TITLE
React Native AppReveal pod fails to compile with Xcode 26.3 / iOS 26.2 SDK

### ISSUE THREAD

**Issue by rafiki270** [UnlikeOtherAI/AppReveal#21]
## Platform
- macOS host building iOS device app
- Xcode: 26.3 (SDK iPhoneOS26.2)
- Target: iPad physical device, Release iphoneos arm64
- AppReveal package path: /System/Volumes/Data/.internal/projects/Projects/AppReveal/ReactNative/appreveal
- Consumer app: POS Diagnostics React Native / Expo prebuild

## Exact command
```sh
EXPO_PUBLIC_POS_DIAGNOSTICS_SERVER_URL=ws://192.168.1.229:4561/api/v1/device/ws \
xcodebuild -quiet \
  -workspace ios/POSDiagnostics.xcworkspace \
  -scheme POSDiagnostics \
  -configuration Release \
  -destination 'generic/platform=iOS' \
  -derivedDataPath /tmp/posdiag-ipad-shot-build \
  -allowProvisioningUpdates \
  DEVELOPMENT_TEAM=59S95D279D \
  CODE_SIGN_STYLE=Automatic \
  build
```

## Failure output
```
/System/Volumes/Data/.internal/projects/Projects/AppReveal/ReactNative/appreveal/ios/InteractionEngine.swift:363:42: error: use of 'type' refers to instance method rather than global function 'type(of:)' in module 'Swift'
.first { !String(describing: type(of: /bin/zsh)).contains("UIInputWindowController") }
note: use 'Swift.' to reference the global function in module 'Swift'

/System/Volumes/Data/.internal/projects/Projects/AppReveal/ReactNative/appreveal/ios/MCPTools.swift:496:5: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
router.register(MCPToolDefinition(

/System/Volumes/Data/.internal/projects/Projects/AppReveal/ReactNative/appreveal/ios/ScreenResolver.swift:137:22: error: no exact matches in call to initializer
return Array(NSOrderedSet(array: overlayWindowModals)) as? [String] ?? overlayWindowModals
Foundation.NSOrderedSet.init note: incorrect labels for candidate (have: '(array:)', expected: '(objects:)')
```

## Steps to reproduce
1. In a React Native/Expo app that links `react-native-appreveal` from `ReactNative/appreveal`, run `expo prebuild --platform ios`.
2. Build the generated workspace for generic iOS device with Xcode 26.3 / iPhoneOS26.2 SDK.
3. The AppReveal pod fails during Swift compilation.

## Notes
This blocks installing the diagnostics test app on a physical iPad for local device testing.

**Comment by rafiki270** [comment]
Fixed in commit f8fb736. Three compile errors addressed:
1. **InteractionEngine**: `Swift.type(of:)` disambiguation for Xcode 26.3
2. **ScreenResolver**: replaced `NSOrderedSet(array:)` with an ordered-preserving `Set<String>` filter — avoids the SDK label change entirely
3. **MCPTools**: same device_info type-check fix as #19
